# NumPy is liner algebra library - indexing and selection

## sudo pip3 install numpy


#### NumPy is Vector and Matrices - Vector is 1D and Matrices is 2D

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]

In [4]:
arr = np.array(my_list) # 1D array

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
my_2d_list = [[1,2,3],[3,4,5],[6,7,8]]

In [8]:
np.array(my_2d_list)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(3) # 1D - uniform distribution

array([0.86522085, 0.26966983, 0.14896903])

In [24]:
np.random.rand(2,3) # 2D - uniform distribution

array([[0.93884697, 0.18766622, 0.67055624],
       [0.96117676, 0.75335539, 0.74332963]])

In [25]:
np.random.randn(3) # 1D normal distribuion

array([ 0.34890621, -0.41126849,  0.59055023])

In [26]:
np.random.randn(2,2)

array([[-0.46679191, -0.0953924 ],
       [-0.38317227, -0.16721824]])

In [27]:
np.random.randint(1,100) # return single value from 1 to 100

97

In [29]:
new_array = np.random.randint(1,100,10) # return 10 values

In [30]:
new_array

array([21, 11,  9, 62, 60, 84, 52, 95, 85, 79])

In [31]:
new_array.reshape(2,5)

array([[21, 11,  9, 62, 60],
       [84, 52, 95, 85, 79]])

In [44]:
sh_array = new_array.reshape(5,2)

In [46]:
sh_array

array([[21, 11],
       [ 9, 62],
       [60, 84],
       [52, 95],
       [85, 79]])

In [47]:
new_array.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [50]:
sh_array.shape # shape of the array

(5, 2)

In [52]:
sh_array.dtype

dtype('int64')

new_array.max()

In [39]:
new_array.min()

9

In [40]:
new_array

array([21, 11,  9, 62, 60, 84, 52, 95, 85, 79])

In [41]:
new_array.argmax() #return index position of max

7

In [42]:
new_array.argmin()

2

## Array Indexing

In [53]:
arr_i = np.arange(10)

In [54]:
arr_i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr_i[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr_i[4:]

array([4, 5, 6, 7, 8, 9])

In [58]:
arr_i[:5]

array([0, 1, 2, 3, 4])

In [60]:
arr_i[-5:]

array([5, 6, 7, 8, 9])

In [61]:
arr_i[-5:-1]

array([5, 6, 7, 8])

In [63]:
arr_i[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
arr_i[::-2]

array([9, 7, 5, 3, 1])

In [65]:
arr_i[::2]

array([0, 2, 4, 6, 8])

In [66]:
arr_i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr_i[1:4] = 100 # this will broad cast the assigned value

In [68]:
arr_i

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [91]:
arr_i2 = np.arange(1,10)

In [92]:
arr_i2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
slice_arr_i2 = arr_i2[:5]

In [94]:
slice_arr_i2

array([1, 2, 3, 4, 5])

In [95]:
slice_arr_i2[::] = 100

In [96]:
slice_arr_i2


array([100, 100, 100, 100, 100])

In [97]:
arr_i2 # this will have single copy  - this is shallow copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

## deep copy

In [98]:
arr_copy_i2 = arr_i2.copy()

In [99]:
arr_copy_i2

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [100]:
arr_i2

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [101]:
arr_copy_i2[:] = 77

In [102]:
arr_i2

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [103]:
arr_copy_i2

array([77, 77, 77, 77, 77, 77, 77, 77, 77])

# 2 - D array

In [105]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [106]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
arr_2d[1][1] # 2 bracket notation

5

In [108]:
arr_2d[1,1]

5

In [109]:
arr_2d[2,0]

7

In [110]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
arr_2d[2:]

array([[7, 8, 9]])

In [114]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

## conditional selection

In [115]:
arr_2d1 = np.arange(0,10)

In [116]:
arr_2d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
bool_arr_2d1 = arr_2d1 > 5

In [118]:
bool_arr_2d1

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [119]:
arr_2d1[bool_arr_2d1]

array([6, 7, 8, 9])

In [120]:
arr_2d1[arr_2d1 < 3]

array([0, 1, 2])

In [123]:
arr_2d2 = np.arange(50).reshape(5,10)

In [124]:
arr_2d2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [125]:
arr_2d2[2,5]

25

In [126]:
arr_2d2[2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [127]:
arr_2d2[2:, 3:]

array([[23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

In [150]:
arr_2d2[2:4,5:8] # to grap the 25 to 27 and 35 to 37

array([[25, 26, 27],
       [35, 36, 37]])

In [153]:
arr_2d2[2:4,5:8] = 100

In [154]:
arr_2d2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24, 100, 100, 100,  28,  29],
       [ 30,  31,  32,  33,  34, 100, 100, 100,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

 # NumPy Operation

In [132]:
arr_o = np.arange(0,11)

In [133]:
arr_o

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr_o + arr_o

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [135]:
arr_o - arr_o

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [136]:
arr_o * arr_o

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [137]:
arr_o 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
arr_o + 100 # scalar 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [139]:
arr_o / arr_o

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [140]:
1/0

ZeroDivisionError: division by zero

In [141]:
arr_o ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [142]:
np.sqrt(arr_o)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [143]:
np.exp(arr_o)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [144]:
np.max(arr_o)

10

In [145]:
np.min(arr_o)

0

In [146]:
arr_o.max()

10

In [147]:
np.sin(arr_o)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [155]:
import numpy as np


In [156]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [157]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [163]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [165]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [167]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [168]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [170]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [171]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### standard normal distribution of 25 random numbers

In [172]:
np.random.randn(25)

array([ 0.62697453,  0.35060965, -0.0512318 , -0.18373657,  0.45736023,
        0.15819949,  1.03595342,  0.09509111, -0.66016277,  0.29773442,
       -0.20811396, -0.57997497,  0.37723483,  0.62462227, -0.19643373,
       -1.18656022, -1.21021733, -0.674631  ,  1.21699466, -0.76153069,
        1.14862035,  0.7826262 ,  0.8485992 , -0.04778455,  0.40837822])

In [185]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [186]:
np.linspace(0.01,1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [187]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [190]:
mat = np.arange(0,10,1).reshape(2,5)

In [191]:
mat

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [192]:
mat.sum()

45

In [193]:
np.sum(mat)

45

In [194]:
mat.std()

2.8722813232690143

In [200]:
mat.sum(axis=0) # sum the 2 rows

array([ 5,  7,  9, 11, 13])

In [201]:
mat.sum(axis=1) # sum the each colum

array([10, 35])